export const products = [
    {
        id: '1',
        name: 'Опора тавровая хомутовая ТХ',
        price: '1849.9',
        gost: 'ГОСТ 14911-82',
        type: 'Опора тавровая',
        img: 'https://svibex.github.io/bastiongroup/image/kh.png',
        amount: 0,
    },
    {
        id: '2',
        name: 'Опора корпусная приварная КП',
        price: '849.9',
        gost: 'ОСТ 36-146-88',
        type: 'Опора корпусная',
        img: 'https://svibex.github.io/bastiongroup/image/kp.png',
        amount: 0,
    },
    {
        id: '3',
        name: 'Опора корпусная хомутовая КХ',
        price: '2849.9',
        gost: 'НТС 65-06',
        type: 'Опора корпусная',
        img: 'https://svibex.github.io/bastiongroup/image/kh.png',
        amount: 0,
    },
    {
        id: '4',
        name: 'Опора подвижная ОПБ1',
        price: '1579.9',
        gost: 'ГОСТ 14911-82',
        type: 'Опора подвижная',
        img: 'https://svibex.github.io/bastiongroup/image/opb1.png',
        amount: 0,
    },
    {
        id: '5',
        name: 'Опора подвижная ОПБ2',
        price: '1650.5',
        gost: 'ГОСТ 14911-82',
        type: 'Опора подвижная',
        img: 'https://svibex.github.io/bastiongroup/image/opb2.png',
        amount: 3,
    }, {
        id: '6',
        name: 'Опора трубчатая ТР',
        price: '345.7',
        gost: 'ГОСТ 14911-82',
        type: 'Опора трубчатая',
        img: 'https://svibex.github.io/bastiongroup/image/tr.png',
        amount: 2,
    },
    {
        id: '7',
        name: 'Опора тавровая приварная ТП',
        price: '715.9',
        gost: 'ГОСТ 14911-82',
        type: 'Опора тавровая',
        img: 'https://svibex.github.io/bastiongroup/image/tp.png',
        amount: 0,
    },
    {
        id: '8',
        name: 'Опора подвижная ОПП3',
        price: '849.9',
        gost: 'ГОСТ 14911-82',
        type: 'Опора подвижная',
        img: 'https://svibex.github.io/bastiongroup/image/opp3.png',
        amount: 0,
    },
    {
        id: '9',
        name: 'Опора подвижная ОПП2',
        price: '850.9',
        gost: 'ГОСТ 14911-82',
        type: 'Опора подвижная',
        img: 'https://svibex.github.io/bastiongroup/image/opp2.png',
        amount: 0,
    },
];

export const productTypes = [
    {id: '1', type: 'Опора тавровая'},
    {id: '2', type: 'Опора корпусная'},
    {id: '3', type: 'Опора подвижная'},
    {id: '4', type: 'Опора трубчатая'}];

export const filters = {price: {min: 0, max: 0}, types: [], gosts: []};
